### ISSUE TITLE
Webcak : [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)

### ISSUE THREAD

**Issue by ramrajg** [opravdin/weback-hass#8] opened 2020-12-26 18:04 UTC
Hi 
I am getting following error 
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)
in home assistants

**Comment by opravdin** [comment] 2021-01-10 02:50
Duplicate of #6

**Closed by opravdin** 2021-01-10 02:50 UTC
